name: Daily Data Update

on:
  schedule:
    - cron: '0 10 * * *' # Runs at 5:00 AM EST every day
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Packages
        run: Rscript -e 'install.packages(c("tidyverse", "janitor", "jsonlite"))'

      - name: Run Scraper
        run: Rscript Daily-Execute-File.R

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add daily_data.csv
          git commit -m "Daily data update: $(date)" || echo "No changes to commit"
          git push